# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbadf803230930dace769dd796cd5033342153d42dc0bf92e3e1b83245d16f6b8a6dc4274e45cb0cec456ba68431f62c67af143050a95537d61288fefc1bd367

test:
  secret_key_base: 539f3c2d35cfbf04f4c135767e4f9e2a6356e018eef6fc6fcc5f0a7a87e0eefd892d835039c932d7203f72f3bc90a0b68473f9597ed737e2ec49a22f7a7ff953

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
